project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "404.qmd"
    - "about/index.qmd"
    - "articles/index.qmd"
    - "projects/index.qmd"
    - "contact/index.qmd"
    - "articles/posts/**/index.qmd"
    - "articles/posts/**/index.md"
    - "articles/posts/**/index.ipynb"
  resources:
    - "projects/**"
    - "media/*"

website:
  title: "Josh Pearlson"
  favicon: media/jcp_logo2.png
  search:
    keyboard-shortcut: ["f"]
  navbar:
    logo: media/jcp_logo3.png
    right:
      - text: "Articles"
        href: articles/
      - text: "Projects"
        href: projects/
      - text: "About"
        href: about/
      - text: "Contact"
        href: contact/
format:
  html:
    theme:
      # cyborg
      # darkly
      slate
      # superhero
      # dark: darkly
      # light: cosmos
    css: css/header.css
    include-after-body:
      - javaScript/console.html
      - javaScript/analytics.html
