project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "404.qmd"
    - "aboutPage/about.qmd"
    - "articles/blog.qmd"
    - "articles/posts/**/*.qmd"
    - "articles/posts/**/*.md"
    - "articles/posts/**/*.ipynb"
    - "projects/projects.qmd"
    - "contact/contact.qmd"
  resources:
    - "projects/**"
    - "media/*"

website:
  title: "Josh Pearlson"
  favicon: media/jcp_logo2.png
  search:
    keyboard-shortcut: ["f"]
  navbar:
    logo: media/jcp_logo3.png
    right:
      - text: "Articles"
        href: articles/blog.qmd
      - text: "Projects"
        href: projects/projects.qmd
      - text: "About"
        href: aboutPage/about.qmd
      - text: "Contact"
        href: contact/contact.qmd
format:
  html:
    theme:
      # cyborg
      # darkly
      slate
      # superhero
      # dark: darkly
      # light: cosmos
    css: css/header.css
    include-after-body:
      - javaScript/console.html
      - javaScript/analytics.html
