<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josh Pearlson">
<meta name="dcterms.date" content="2024-08-16">

<title>Modeling a Coin Flip Game – Josh Pearlson</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../media/jcp_logo2.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../css/header.css">
<link rel="stylesheet" href="../../../css/posts.css">
<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed jcp-article-page fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../media/jcp_logo3.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Josh Pearlson</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../articles/"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about/"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../contact/"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Modeling a Coin Flip Game</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Python</div>
                <div class="quarto-category">Probability</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Josh Pearlson </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 16, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>A casino offers a game: Flip a coin as long as you want. Your prize is the ratio of heads to total flips. What’s your strategy to maximize your winnings?</p>
<section id="coin-flip-game" class="level2">
<h2 class="anchored" data-anchor-id="coin-flip-game">Coin Flip Game</h2>
<p>Imagine you’re in a casino. Instead of slot machines or table games, a dealer offers you a coin game and explains the rules:</p>
<blockquote class="blockquote">
<p>I will pay you based on the outcome of a coin flip game. You can flip the coin as <strong>many times as you want</strong>, and you can <strong>stop whenever you like</strong>. I will pay you based on the ratio of heads to total flips. I will <strong>charge you 75 cents to play</strong> and <strong>pay you one dollar multiplied by your heads-to-total-flips ratio</strong>. Would you like to play?</p>
</blockquote>
<p>At first glance it appears the casino is offering us a losing wager (as is typical). In any long-run scenario you would expect to get a ratio of 1/2 heads to total flips, since heads and tails are equally likely to occur on any given flip. In that case, we would be paying 75 cents to play a game where we would only be getting paid 50 (1 heads for every 1 tails) cents! That calculation assumes we keep flipping. We can also choose to stop, so we need to account for that choice.</p>
</section>
<section id="basic-strategy" class="level2">
<h2 class="anchored" data-anchor-id="basic-strategy">Basic Strategy</h2>
<p>First, let’s review the problem: We have a fair coin (50% heads, 50% tails) and we can flip it as many times as we want. Our goal is to maximize the ratio of heads to total flips.</p>
<p>First, we should think about a simplified case to get a better understanding of the game dynamics. We will create a decision tree to visualize our options following the outcome of the first flip:</p>
<pre><code>Start Game
     |
     +-- Flip 1: Heads (50% chance)
     |     |
     |     +-- Ratio is 1.0 (1 head / 1 flip)
     |     +-- DECISION: STOP. This is the best possible ratio.
     |     +-- OUTCOME: Profit (1.0 payout &gt; 0.75 cost)
     |
     +-- Flip 1: Tails (50% chance)
           |
           +-- Ratio is 0.0 (0 heads / 1 flip)
           +-- DECISION: CONTINUE. Stopping means a 0.0 payout.
                 |
                 +-- Keep flipping...
                 +-- Long-run ratio approaches 0.5
                 +-- OUTCOME: Loss (0.5 payout &lt; 0.75 cost)</code></pre>
<p>When we flip heads on the first flip we win the game outright with the best possible payout ratio of 1.0 heads/total flips (giving us the game’s maximum profit of 100 (payout) - 75 (cost) = 25 cents). However if we flip tails on the first flip we are in a losing situation where we will have to continue flipping, for now, consider stopping at a fixed, very large number of flips after an initial tail. The expected ratio then approaches 0.5 from below as that cutoff grows. A limiting ratio is not itself a finite stopping time.</p>
<p>In the limit, half the games pay a profit of 25 cents immediately, and the other half have an expected loss approaching 25 cents. Finite cutoffs can approach a break-even expected value arbitrarily closely. Thus the supremum of expected profit over stopping rules satisfies:</p>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
\sup EV_{game} &amp;\geq  \\
&amp;\frac{1}{2} (1.0 - 0.75) +
\frac{1}{2} (0.5 - 0.75)  \\
&amp;= \frac{1}{2} (0.25) +
\frac{1}{2} (-0.25) \\
&amp;= \$0
\end{aligned}
\]</span></p>
</div>
<p>If we wish to improve on this strategy we need to consider a new approach. What if we consider stopping at the first time that we see we have flipped heads more often than tails?</p>
<section id="stop-when-heads-tails-strategy" class="level3">
<h3 class="anchored" data-anchor-id="stop-when-heads-tails-strategy">Stop When Heads &gt; Tails Strategy</h3>
<p>I will create a table with the first couple of possible stopping points (locations where # heads &gt; # tails) for this game:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 34%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Flip Sequence</th>
<th>Heads</th>
<th>Tails</th>
<th>Ratio (Heads/Total Flips)</th>
<th>Probability of sequence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H</td>
<td>1</td>
<td>0</td>
<td>1.0</td>
<td>1/2</td>
</tr>
<tr class="even">
<td>T H H</td>
<td>2</td>
<td>1</td>
<td>0.67</td>
<td>1/2 ^3</td>
</tr>
<tr class="odd">
<td>T T H H H</td>
<td>3</td>
<td>2</td>
<td>0.60</td>
<td>1/2 ^5</td>
</tr>
<tr class="even">
<td>T H T H H</td>
<td>3</td>
<td>2</td>
<td>0.60</td>
<td>1/2 ^5</td>
</tr>
</tbody>
</table>
<p>From the table above we can see that if we stop at the first time we have more heads than tails we can achieve a ratio of 1.0, .67, .60, etc. Each stopping point is less and less likely, there is <span class="math inline">\(\frac{1}{2}^{\text{\# total flips}}\)</span> chance of achieving each outcome. However, we can see that the ratios we achieve are all greater than 0.5 heads/total flips. Another thing we notice is that the longer sequences clearly have many more paths (at much lower likelihoods) than the shorter sequences.</p>
<p>Let’s plot the possible outcomes of this game to count the number of paths that lead to each outcome:</p>
<div id="cell-2" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2026-09-16T12:40:10.156924Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-09-16T12:40:10.156729Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-09-16T12:40:10.441101Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-09-16T12:40:10.440625Z&quot;}" data-execution_count="1">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-2-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As we can see above, we have the blue line showing the threshold where the number of heads and tails flipped are equal. The red dots are showing us our stopping points, where we have flipped more heads than tails for the first time. Only valid paths from (0,0) to each red dot without crossing the blue line are possible outcomes of the strategy! We also know that each time we flip a coin N times our chance of getting one exact path is 1/2^N. Given this graphical representation we can now use combinatorics to count the number of paths that lead to each stopping point and multiply this by our probability of getting to that same path.</p>
<p>For some arbitrary number k, we will stop when we have flipped k+1 heads and k tails. The total number of flips will be 2k+1 and our heads/total flips ratio will be (k+1)/(2k+1).</p>
<p>The EV of this game can be calculated as the sum of each stopping-point ratio multiplied by the probability of reaching that ratio minus the cost to play (75 cents).</p>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
EV_{game} &amp;= \sum_{k=0}^{\infty} \left( \frac{\text{Heads}}{\text{Total Flips}} \cdot P(k) \right) - 0.75 \\
EV_{game} &amp;= \sum_{k=0}^{\infty} \left( \frac{k+1}{2k+1} \cdot P(k) \right) - 0.75 \\
\end{aligned}
\]</span></p>
</div>
<p>How do we calculate P(k)? We can count paths in the diagram above. Here we can see that there are a number of paths that lead to each stopping point. However not all paths are valid, since some paths cross the blue line (where heads = tails) before reaching the stopping point. To calculate the number of valid paths to each stopping point we can use the ballot theorem from combinatorics.</p>
<blockquote class="blockquote">
<p>The <a href="https://en.wikipedia.org/wiki/Bertrand%27s_ballot_theorem">ballot theorem</a> states that if in an election candidate A receives h votes and candidate B receives k votes with h&gt;k, then the number of ways the votes can be counted such that A is always strictly ahead of B is given by:</p>
</blockquote>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
\frac{h-k}{h+k} \binom{h+k}{k} \\
\end{aligned}
\]</span></p>
</div>
<p>A special case of this theorem is when h = k + 1, exceeding votes by exactly one. To connect this to our stopping rule, reverse a valid flip sequence. A path that first reaches a heads surplus of one on its final flip becomes a reversed path with heads strictly ahead at every step. This gives a one-to-one correspondence with the ballot theorem’s paths. Let’s now solve for this special case:</p>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
% &amp; \frac{h-k}{h+k} \binom{h+k}{k} \\
&amp; h = k + 1 \\
&amp; \text{Substituting h for its new value of k + 1}  \\
&amp; = \frac{(k+1)-k}{(k+1)+k} \binom{(k+1)+k}{k} \\
&amp; = \frac{1}{2k+1} \binom{2k+1}{k} \\
&amp; = \frac{1}{2k+1} \cdot \frac{(2k+1)!}{(k+1)! k!} \\
&amp; (2k+1)! = (2k+1)((2k)!) \\
&amp; = \frac{1}{2k+1} \cdot \frac{(2k+1)((2k)!)}{(k+1)! k!} \\
&amp; = \frac{(2k)!}{(k+1)! k!} \\
&amp; (k+1)! = (k+1)(k!) \\
&amp; = \frac{(2k)!}{(k+1)(k!) k!} \\
&amp; = \frac{1}{k+1} \cdot \frac{(2k)!}{k! k!} \\
&amp; = \frac{1}{k+1} \binom{2k}{k} \\
\end{aligned}
\]</span></p>
</div>
<p>The sequence we have arrived at above is the sequence in combinatorics called the <a href="https://en.wikipedia.org/wiki/Catalan_number">Catalan numbers</a>. Catalan numbers have many applications in combinatorial mathematics including counting valid parentheses expressions, counting rooted binary trees, and <strong>counting paths in a grid that do not cross a diagonal line</strong>. In our case we are using them to count the number of valid paths to each stopping point in our coin flip game. The number of paths to the k-th number stopping point (where num heads = k + 1 and num tails = k) happens to be the k-th Catalan number!</p>
<p>Let’s calculate the expected value of the stop when heads exceeds tails by one strategy.</p>
</section>
<section id="calculating-ev-of-stop-when-heads-tails" class="level3">
<h3 class="anchored" data-anchor-id="calculating-ev-of-stop-when-heads-tails">Calculating EV of Stop When Heads &gt; Tails</h3>
<p>Strategy: Let each stopping point k be defined as the first time # heads = k + 1 and # tails = k. In this game we are paid out based on the number of heads / total flips ratio at some stopping point k. As defined previously the value at the k-th stopping is (k + 1) / (2k + 1). The probability of reaching this stopping point is equal to the number of valid paths to this stopping point (equivalent to the kth Catalan number) multiplied by the probability of reaching any one path (1/2^(total flips) = (1/2 ^ (2k+1)). We also know that the EV of the game is equal to the payout minus the cost to play the game (75 cents). First let’s calculate the expected payout (EP) of this strategy:</p>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{\text{Heads}}{\text{Total Flips}} \cdot P(k) \right) \\
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{k+1}{2k+1} \cdot P(k) \right) \\
P(k) &amp;= C_k \cdot \left( \frac{1}{2} \right)^{2k+1} \\
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{k+1}{2k+1} \cdot C_k \cdot \left( \frac{1}{2} \right)^{2k+1} \right) \\
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{k+1}{2k+1} \cdot \frac{1}{k+1} \binom{2k}{k} \cdot \left( \frac{1}{2} \right)^{2k+1} \right) \\
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{1}{2k+1} \cdot \binom{2k}{k} \cdot \left( \frac{1}{2} \right)^{2k+1} \right) \\   
EP_{strategy} &amp;= \sum_{k=0}^{\infty} \left( \frac{1}{2k+1} \cdot \frac{(2k)!}{(k!)^2} \cdot \left( \frac{1}{2} \right)^{2k+1} \right) \\
&amp;\text{After further simplification we arrive at:} \\
EP_{strategy} &amp;= \frac{1}{2} * \sum_{k=0}^{\infty} \left( \frac{\binom{2k}{k}}{4^k (2k+1)} \right) \\
\end{aligned}
\]</span></p>
</div>
<p>Here we use the fact that the sum above is equal to the Taylor series expansion of arcsin(x) evaluated at x = 1. The result is as follows:</p>
<div style="text-align: left;">
<p><span class="math display">\[
\begin{aligned}
\arcsin(x) &amp;= \sum_{k=0}^{\infty} \left( \frac{\binom{2k}{k}}{4^k (2k+1)} x^{2k+1} \right) \\
\arcsin(1) &amp;= \sum_{k=0}^{\infty} \left( \frac{\binom{2k}{k}}{4^k (2k+1)}  \right) \\
\arcsin(1) &amp;= \frac{\pi}{2} \\
\frac{\pi}{2} &amp;= \sum_{k=0}^{\infty} \left( \frac{\binom{2k}{k}}{4^k (2k+1)} \right)\\
EP_{strategy} &amp;= \frac{1}{2} * \frac{\pi}{2} = \frac{\pi}{4} \approx 0.7854 \\
EV_{strategy} &amp;= EP_{strategy} - \text{Cost to Play} \\
EV_{strategy} &amp;= \frac{\pi}{4} - 0.75 \approx 0.0354 \\
\end{aligned}
\]</span></p>
</div>
<p>This strategy has a positive expected profit. By stopping the first time heads exceeds tails, we get an expected profit of about 3.54 cents per game. This stopping time is finite with probability one, but its expected number of flips is infinite. A positive expected profit per game therefore does not imply a useful hourly return. This would be a ROI of about 4.72% on each 75 cent wager!</p>
</section>
</section>
<section id="strategy-improvement" class="level2">
<h2 class="anchored" data-anchor-id="strategy-improvement">Strategy Improvement</h2>
<p>The ‘stop when heads &gt; tails’ strategy clearly works, however, it seems like there could be a better strategy. What if we only accept a heads/total flips ratio of greater than 0.51, or 0.55, or 0.60? Could we do even better?</p>
<p>In this exploration two things interest me most:</p>
<ol type="1">
<li>What is the optimal policy for the ‘stop when heads/total flips &gt; X’ strategy?</li>
<li>Is there a better policy that could outperform stop when ‘heads/total flips &gt; X’?</li>
</ol>
<p>First, let’s evaluate a threshold strategy with a <strong>50-cent fallback</strong>. Flips are independent and fair, and there is no time limit or cost per flip:</p>
<ol type="1">
<li>Stop if heads/total flips exceeds the chosen threshold during the first <span class="math inline">\(N\)</span> flips.</li>
<li>If the threshold has not been reached by <span class="math inline">\(N\)</span>, collect the current ratio if it is at least one half.</li>
<li>Otherwise, keep flipping until heads and tails are equal, then collect 50 cents.</li>
</ol>
<p>The law of large numbers says the heads ratio converges to one half with probability one. To justify collecting exactly 50 cents at a finite stopping time, we use another fact: a <a href="https://math.dartmouth.edu/~doyle/docs/walks/walks.pdf">symmetric random walk is recurrent</a>. Starting from any finite deficit, heads eventually catches up with tails with probability one. The waiting time is finite almost surely, but its expectation is infinite.</p>
<p>That makes <span class="math inline">\(\max(0.5,h/N)\)</span> a valid fallback payout after <span class="math inline">\(N\)</span> flips with <span class="math inline">\(h\)</span> heads. Below one half, this represents continuing to a tie, not collecting money before earning it. The calculation can account for that eventual payout without simulating the extra flips. Here <span class="math inline">\(N\)</span> ends the threshold phase; it is <strong>not a limit on the game’s total flips</strong>.</p>
<p>This is a specific two-stage strategy. It differs from continuing to chase the original threshold forever. I will evaluate it by propagating the probability of each possible heads count, avoiding sampling noise.</p>
<section id="python-simulation-for-stop-when-headstotal-flips-x-strategy" class="level3">
<h3 class="anchored" data-anchor-id="python-simulation-for-stop-when-headstotal-flips-x-strategy">Python Calculation for ‘Stop When Heads/Total Flips &gt; X’</h3>
<p>For each live state after <span class="math inline">\(n\)</span> flips, half its probability goes to the same heads count after a tail, and half goes to one additional head. When a state stops, add its probability times its payout to the total and remove it from future flips. This sums over paths without storing each path separately. The calculation is deterministic, with ordinary floating-point rounding.</p>
<div id="cell-5" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2026-09-16T12:40:10.688854Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-09-16T12:40:10.688703Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-09-16T12:40:12.260662Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-09-16T12:40:12.259861Z&quot;}" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate_threshold(threshold_percent: <span class="bu">int</span>, switch_after: <span class="bu">int</span>):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Follow a threshold, then collect at least half by waiting for a tie if needed."""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> <span class="dv">0</span> <span class="op">&lt;=</span> threshold_percent <span class="op">&lt;=</span> <span class="dv">100</span> <span class="kw">or</span> switch_after <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Use a threshold from 0 to 100 and a positive number of threshold-phase flips."</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    live <span class="op">=</span> np.array([<span class="fl">1.0</span>])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    expected_payout <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    fallback_probability <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> n <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, switch_after <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        following <span class="op">=</span> np.zeros(n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        following[:<span class="op">-</span><span class="dv">1</span>] <span class="op">+=</span> <span class="fl">0.5</span> <span class="op">*</span> live  <span class="co"># Tail: heads count stays the same.</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        following[<span class="dv">1</span>:] <span class="op">+=</span> <span class="fl">0.5</span> <span class="op">*</span> live   <span class="co"># Head: heads count increases by one.</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        heads <span class="op">=</span> np.arange(n <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Integer comparison avoids rounding at exact threshold ties.</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        stop <span class="op">=</span> <span class="dv">100</span> <span class="op">*</span> heads <span class="op">&gt;</span> threshold_percent <span class="op">*</span> n</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        payouts <span class="op">=</span> heads <span class="op">/</span> n</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> n <span class="op">==</span> switch_after:</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>            fallback_probability <span class="op">=</span> <span class="bu">float</span>(following[<span class="op">~</span>stop].<span class="bu">sum</span>())</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Below half, continue past switch_after until heads and tails tie.</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Recurrence gives an eventual payout of exactly 0.5, almost surely.</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>            payouts[<span class="op">~</span>stop] <span class="op">=</span> np.maximum(<span class="fl">0.5</span>, payouts[<span class="op">~</span>stop])</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>            stop <span class="op">=</span> np.ones(n <span class="op">+</span> <span class="dv">1</span>, dtype<span class="op">=</span><span class="bu">bool</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        expected_payout <span class="op">+=</span> <span class="bu">float</span>(np.dot(following[stop], payouts[stop]))</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>        following[stop] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>        live <span class="op">=</span> following</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> expected_payout, fallback_probability</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>switch_points <span class="op">=</span> (<span class="dv">100</span>, <span class="dv">1000</span>, <span class="dv">5000</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> []</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> switch_after <span class="kw">in</span> switch_points:</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> threshold_percent <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">50</span>, <span class="dv">65</span>):</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        payout, fallback_probability <span class="op">=</span> evaluate_threshold(threshold_percent, switch_after)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>        results.append({</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Threshold-phase flips"</span>: switch_after,</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Stop ratio"</span>: threshold_percent <span class="op">/</span> <span class="dv">100</span>,</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Expected payout"</span>: payout,</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Expected profit"</span>: payout <span class="op">-</span> <span class="fl">0.75</span>,</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Fallback probability"</span>: fallback_probability,</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>        })</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>df_all_results <span class="op">=</span> pd.DataFrame(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-6" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2026-09-16T12:40:12.262050Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-09-16T12:40:12.261935Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-09-16T12:40:12.342886Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-09-16T12:40:12.342446Z&quot;}" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-7" class="cell" data-execution="{&quot;iopub.execute_input&quot;:&quot;2026-09-16T12:40:12.344142Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-09-16T12:40:12.344059Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-09-16T12:40:12.350896Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-09-16T12:40:12.350301Z&quot;}" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Expected payout</th>
<th data-quarto-table-cell-role="th">Expected profit</th>
<th data-quarto-table-cell-role="th">Fallback probability</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Stop ratio</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.50</td>
<td>0.785394</td>
<td>0.035394</td>
<td>0.025225</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.51</td>
<td>0.785902</td>
<td>0.035902</td>
<td>0.042522</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.52</td>
<td>0.786731</td>
<td>0.036731</td>
<td>0.066234</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.53</td>
<td>0.787478</td>
<td>0.037478</td>
<td>0.091053</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.54</td>
<td>0.788079</td>
<td>0.038079</td>
<td>0.115600</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.55</td>
<td>0.788447</td>
<td>0.038447</td>
<td>0.139108</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.56</td>
<td>0.788757</td>
<td>0.038757</td>
<td>0.161203</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.57</td>
<td>0.788417</td>
<td>0.038417</td>
<td>0.176643</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.58</td>
<td>0.788744</td>
<td>0.038744</td>
<td>0.201132</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.59</td>
<td>0.788212</td>
<td>0.038212</td>
<td>0.216866</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.60</td>
<td>0.788294</td>
<td>0.038294</td>
<td>0.251848</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.61</td>
<td>0.787793</td>
<td>0.037793</td>
<td>0.258422</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.62</td>
<td>0.786928</td>
<td>0.036928</td>
<td>0.270484</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0.63</td>
<td>0.785938</td>
<td>0.035938</td>
<td>0.286057</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.64</td>
<td>0.784944</td>
<td>0.034944</td>
<td>0.296924</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>With the fallback starting after 1,000 flips, the 0.50 threshold pays about <span class="math inline">\(0.785394\)</span> dollars on average, close to the <span class="math inline">\(\pi/4 \approx 0.785398\)</span> payout from waiting until heads first exceeds tails. The values differ because the fallback can stop at a tie, whereas the original rule waits for a heads surplus.</p>
<p>Among the thresholds tested, 0.56 gives the highest expected payout with this switch point: approximately <span class="math inline">\(0.788757\)</span>, or <strong>3.88 cents of expected profit</strong> on the 75-cent entry fee. About <strong>16.12%</strong> of games reach the fallback stage without crossing the threshold. Some can collect immediately; those below one half continue until a tie.</p>
<p>The plot also compares fallback switch points of 100 and 5,000 flips. Keeping a fixed threshold for longer does not necessarily improve its expected payout. These results compare the stated two-stage strategies, not all possible stopping rules.</p>
</section>
<section id="the-most-optimal-policy" class="level3">
<h3 class="anchored" data-anchor-id="the-most-optimal-policy">Could a Different Stopping Rule Do Better?</h3>
<p>Yes. A fixed ratio ignores how many flips have occurred. Let <span class="math inline">\(V_N(h,n)\)</span> be the best expected payout after <span class="math inline">\(n\)</span> flips, of which <span class="math inline">\(h\)</span> were heads, when we can choose when to stop before switching to the same fallback at <span class="math inline">\(N\)</span>. The fallback value is:</p>
<p><span class="math display">\[V_N(h,N)=\max\left(\frac{h}{N},\frac{1}{2}\right).\]</span></p>
<p>Before then, compare stopping now with the expected value of one more flip:</p>
<p><span class="math display">\[V_N(h,n)=\max\left(\frac{h}{n},\;\frac{V_N(h+1,n+1)+V_N(h,n+1)}{2}\right),\qquad 1\leq n&lt;N.\]</span></p>
<p>Working backward through these states finds the optimal policy within this class, where the fallback takes over at <span class="math inline">\(N\)</span>. It does not optimize decisions after that point; the fallback rule is fixed. The entry fee is already paid, so it does not affect the stop-or-continue comparison. The unlimited-time version is the <a href="https://arxiv.org/abs/1201.0626">Chow–Robbins game</a>, which requires more care than choosing a single ratio.</p>
<p>What about waiting for an almost-all-heads result? That brings us to the infinite monkey theorem.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../media/Chimpanzee_seated_at_typewriter.jpg" class="img-fluid figure-img"></p>
<figcaption>Infinite Monkey Theorem</figcaption>
</figure>
</div>
<p>An endless sequence of independent fair coin flips contains every particular finite pattern with probability one. But a long run of heads somewhere in the sequence does not erase the tails that came before it. Our payout uses <strong>all flips since the start</strong>, not a favorable stretch we select afterward.</p>
<p>For example, after an initial tail the cumulative ratio can never equal one at any finite stopping time. More generally, the cumulative heads ratio converges to one half with probability one. The infinite monkey theorem therefore does not guarantee an eventual near-100% payout. Allowing more time can improve a stopping strategy, but it does not justify the claimed 25-cent guaranteed profit.</p>
</section>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<p>The option to stop changes this game’s expected payout. A player can choose when to collect their winnings instead of accepting the long-run heads ratio and its 50-cent payout.</p>
<section id="analytical-solution" class="level3">
<h3 class="anchored" data-anchor-id="analytical-solution">Analytical Solution</h3>
<p>Stopping the first time heads exceeds tails gives an expected payout of π/4 ≈ 0.7854. We derived this using Catalan numbers to count the paths to each stopping point. With a cost of 0.75, the expected profit is approximately 3.54 cents per game.</p>
</section>
<section id="numerical-results" class="level3">
<h3 class="anchored" data-anchor-id="numerical-results">Numerical Results</h3>
<p>Probability propagation evaluates fixed thresholds followed by a 50-cent fallback. With the fallback starting after 1,000 flips, the best threshold tested is 0.56, with an expected payout of approximately <span class="math inline">\(0.788757\)</span> and expected profit of 3.88 cents. Games below one half at that point continue until a tie. This is the value of the stated strategy, not the optimal value of the unlimited game.</p>
</section>
<section id="the-value-of-optionality" class="level3">
<h3 class="anchored" data-anchor-id="the-value-of-optionality">The Value of Optionality</h3>
<p>The long-run probability of heads is 50%, but the player can stop when the observed heads ratio is higher. The stopping rule determines how much that choice is worth.</p>
</section>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">Future Work</h2>
<p>The numerical comparison above uses a fixed ratio as the stopping threshold. There are several ways to extend this analysis.</p>
<section id="dynamic-stopping-policy" class="level3">
<h3 class="anchored" data-anchor-id="dynamic-stopping-policy">Dynamic Stopping Policy</h3>
<p>The backward recursion above uses both the number of heads and the total number of flips. Implementing it would let us compare a state-dependent policy with the fixed thresholds. A 52% ratio after 1,000 flips changes less after another flip than a 52% ratio after only 25 flips. The decision is whether the expected benefit of continuing exceeds the payout available now.</p>
</section>
<section id="analysis-with-a-biased-coin" class="level3">
<h3 class="anchored" data-anchor-id="analysis-with-a-biased-coin">Analysis with a Biased Coin</h3>
<p>A biased coin (where P(Heads) ≠ 0.5) would require recalculating the expected values and would likely change the optimal stopping thresholds.</p>
</section>
<section id="risk-adjusted-strategies" class="level3">
<h3 class="anchored" data-anchor-id="risk-adjusted-strategies">Risk-Adjusted Strategies</h3>
<p>This analysis focuses on expected value. A player might instead care about the probability of breaking even or avoiding a large loss. Utility theory could help compare strategies for those preferences.</p>
</section>
<section id="different-payout-structures" class="level3">
<h3 class="anchored" data-anchor-id="different-payout-structures">Different Payout Structures</h3>
<p>How would the strategy change if the casino changed its payout function? We could examine non-linear payouts (e.g., (heads/total_flips)^2) or different entry costs to see how the stopping rule changes.</p>
<hr>
<p>These are just some initial thoughts by me and I am open to discussion. As always, feel free to reach out to <a href="mailto:jcp@joshpearlson.com">me</a> for suggestions on future articles or comments.</p>


</section>
</section>

</main> <!-- /main -->
<script>
  <!-- A message to others like me! -->
  console.log("Nice, I also love checking on page elements!");
  console.log("If you're reading this, awesome!");
  console.log(
    "Interested in learning how to make sites like this? Check out quarto.org",
  );
  console.log("They have awesome docs and are a great place to start from!");
  console.log("Signing off. -JP");
</script>
<script data-goatcounter="https://joshpearlson.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>
<script>
// The article theme class is rendered on <body> by posts/_metadata.yml.
// End-of-body scripts can run after a paint, especially behind chart scripts.

const _vp = document.querySelector('meta[name="viewport"]');
if (_vp && !_vp.content.includes('viewport-fit')) {
  _vp.content += ', viewport-fit=cover';
}

document.addEventListener('DOMContentLoaded', function() {
  if (!document.querySelector('.quarto-title-banner')) return;

  const parts = location.pathname.split('/').filter(Boolean);
  if (/^index\.html?$/.test(parts[parts.length - 1])) parts.pop();
  const slug = parts[parts.length - 1] || 'article';
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const titleEl = document.querySelector('.quarto-title h1');
  const title = titleEl ? titleEl.textContent.trim() : slug;
  let date = '';
  document.querySelectorAll('.quarto-title-meta-heading').forEach((h, i) => {
    if (h.textContent.trim() === 'Published') {
      const contents = document.querySelectorAll('.quarto-title-meta-contents');
      if (contents[i]) date = contents[i].textContent.trim();
    }
  });
  const catEls = document.querySelectorAll('.quarto-category');
  const cats = Array.from(catEls).map(e => e.textContent.trim());

  const tabs = ['home','about','articles','projects','contact'];
  const hrefs = {
    home: '/', about: '/about/',
    articles: '/articles/', projects: '/projects/',
    contact: '/contact/'
  };
  const tabsHTML = tabs.map(t => {
    const active = t === 'articles' ? ' t-tab-active' : '';
    const indicator = t === 'articles' ? '&#9656;' : '&nbsp;';
    return `<a href="${hrefs[t]}" class="t-tab${active}"${t === 'articles' ? ' aria-current="page"' : ''}><span class="t-tab-indicator">${indicator}</span>${t}</a>`;
  }).join('');

  const tabBar = document.createElement('div');
  tabBar.className = 'jcp-article-tabbar';
  tabBar.innerHTML = `<div class="t-tabs" role="navigation" aria-label="Main navigation">
    ${tabsHTML}
    <div class="t-tabs-spacer"></div>
    <div class="t-title">jcp@joshpearlson: ~/articles/${esc(slug)}</div>
  </div>`;
  document.body.prepend(tabBar);

  const statusBar = document.createElement('div');
  statusBar.className = 'jcp-article-statusbar';
  statusBar.innerHTML = `<div class="t-status">
    <span><span class="t-status-dot">&#9679;</span> reading</span>
    <span id="t-art-read-time"></span>
    <span class="t-status-weather" id="t-status-weather">
      New York, NY
    </span>
  </div>`;
  document.body.append(statusBar);

  const catChips = cats.map(c => `<span class="t-chip">${esc(c)}</span>`).join('');
  const articleHeader = document.createElement('div');
  articleHeader.className = 't-art-header';
  articleHeader.innerHTML = `
    <div class="t-art-prompt"><span class="t-prompt">$</span> cat ./${esc(slug)}.md</div>
    <h1 class="t-art-title">${esc(title)}</h1>
    <div class="t-art-meta">
      <span class="t-art-date">${esc(date)}</span>
      ${catChips}
    </div>
    <div class="t-art-rule"></div>
  `;

  const main = document.querySelector('main#quarto-document-content');
  if (main) main.prepend(articleHeader);

  document.body.style.removeProperty('padding-top');

  fetch('https://api.open-meteo.com/v1/forecast?latitude=40.7128&longitude=-74.0060&current=temperature_2m,weather_code&temperature_unit=fahrenheit')
    .then(r => r.json())
    .then(d => {
      const temp = Math.round(d.current.temperature_2m);
      const w = document.getElementById('t-status-weather');
      if (w && Number.isFinite(temp)) w.textContent = `NYC ${temp}°F`;
    }).catch(() => {});

  const articleText = main ? main.textContent : '';
  const words = articleText.trim().split(/\s+/).length;
  const mins = Math.max(1, Math.round(words / 220));
  const rt = document.getElementById('t-art-read-time');
  if (rt) rt.textContent = `~${mins} min read`;
});
</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Don't run on the main listing page
  if (document.querySelector('.quarto-listing-container-default')) {
    return;
  }

  const contentArea = document.querySelector('main#quarto-document-content');
  if (!contentArea) return;

  // --- 1. GATHER METADATA ---
  const title = document.querySelector('.quarto-title.column-body h1.title')?.textContent.trim() || 'Article';
  let author = 'Josh Pearlson';
  let date = '';
  const url = window.location.href;

  const metaHeadings = document.querySelectorAll('.quarto-title-meta-heading');
  metaHeadings.forEach(heading => {
    const headingText = heading.textContent.trim();
    const contentsEl = heading.nextElementSibling;
    if (contentsEl && contentsEl.classList.contains('quarto-title-meta-contents')) {
      if (headingText === 'Author') author = contentsEl.querySelector('p')?.textContent.trim() || author;
      if (headingText === 'Published') date = contentsEl.querySelector('p.date')?.textContent.trim() || date;
    }
  });

  // --- 2. BUILD COMBINED FOOTER ---
  const footer = document.createElement('div');
  footer.className = 'article-footer';

  // Subscribe section (left)
  const subscribeSection = document.createElement('div');
  subscribeSection.className = 'subscribe-section';
  subscribeSection.innerHTML = `
    <p class="subscribe-label">Get notified when a new article drops.</p>
    <form action="https://buttondown.com/api/emails/embed-subscribe/jcp"
          method="post"
          class="subscribe-form"
          target="_blank">
      <input type="email" name="email" placeholder="your@email.com" aria-label="Email address" autocomplete="email" required />
      <button type="submit">Subscribe →</button>
    </form>
  `;

  subscribeSection.querySelector('form').addEventListener('submit', function() {
    if (window.goatcounter && window.goatcounter.count) {
      window.goatcounter.count({ path: 'subscribe-article', title: 'Newsletter Signup - Article', event: true });
    }
  });

  // Share button (right)
  const shareContainer = document.createElement('div');
  shareContainer.className = 'share-article-container';

  const shareButton = document.createElement('button');
  shareButton.className = 'share-article-button';
  shareButton.textContent = 'Share this Article';

  shareContainer.appendChild(shareButton);

  footer.appendChild(subscribeSection);
  footer.appendChild(shareContainer);
  contentArea.appendChild(footer);

  // --- 3. SHARE CLICK HANDLER ---
  shareButton.addEventListener('click', function() {
    const shareText = `"${title}" by ${author} (Published: ${date}): ${url}`;
    navigator.clipboard.writeText(shareText).then(() => {
      const originalText = shareButton.textContent;
      shareButton.textContent = 'Copied to clipboard!';
      shareButton.classList.add('copied');
      setTimeout(() => {
        shareButton.textContent = originalText;
        shareButton.classList.remove('copied');
      }, 3000);
    }).catch(() => {
      const originalText = shareButton.textContent;
      shareButton.textContent = 'Copy failed!';
      setTimeout(() => { shareButton.textContent = originalText; }, 3000);
    });
  });
});
</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  // Only run on post pages (where there is a title banner)
  if (!document.querySelector('.quarto-title-banner')) return;

  const mainContainer = document.querySelector('#quarto-content');
  const articleContent = mainContainer?.querySelector('main#quarto-document-content');
  if (!articleContent) return;

  const headings = articleContent.querySelectorAll('h2, h3');
  if (headings.length < 2) return;

  // --- 1. CREATE THE TOC STRUCTURE ---
  const tocNav = document.createElement('nav');
  tocNav.className = 'scrollspy-nav';

  const tocHeader = document.createElement('p');
  tocHeader.className = 'scrollspy-header';
  tocHeader.textContent = 'Contents';
  tocNav.appendChild(tocHeader);

  const tocList = document.createElement('ol');
  tocList.className = 'scrollspy-list';

  headings.forEach(heading => {
    if (!heading.id) {
      const slug = heading.textContent.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');
      heading.id = slug;
    }

    const tocItem = document.createElement('li');
    tocItem.className = `scrollspy-item toc-level-${heading.tagName.toLowerCase()}`;

    const tocLink = document.createElement('a');
    tocLink.href = `#${heading.id}`;
    tocLink.textContent = heading.textContent;
    tocLink.className = 'scrollspy-link';

    tocItem.appendChild(tocLink);
    tocList.appendChild(tocItem);
  });

  tocNav.appendChild(tocList);
  mainContainer.prepend(tocNav);

  // --- 2. SCROLL-BASED HIGHLIGHT LOGIC ---
  const tocLinks = tocList.querySelectorAll('.scrollspy-link');
  // Match the fixed terminal tab bar, including direct section-anchor links.
  const navbar = document.querySelector('.jcp-article-tabbar');
  const OFFSET = (navbar ? navbar.offsetHeight : 56) + 32;

  // When the user clicks a TOC link, we lock onto that heading ID.
  // The lock only releases once the scroll naturally catches up to that section,
  // preventing the scroll listener from overriding the click mid-animation.
  let lockedHeadingId = null;

  function setActive(link) {
    tocLinks.forEach(l => l.classList.remove('active'));
    if (link) link.classList.add('active');
  }

  function getCurrentHeading() {
    let current = null;
    headings.forEach(heading => {
      if (heading.getBoundingClientRect().top <= OFFSET) {
        current = heading;
      }
    });
    return current || headings[0];
  }

  function updateActive() {
    const current = getCurrentHeading();

    // If we clicked a link, hold on that heading until the scroll
    // naturally arrives at it — then release the lock
    if (lockedHeadingId) {
      if (current.id === lockedHeadingId) {
        lockedHeadingId = null; // arrived — hand back to scroll tracking
      } else {
        return; // still animating, don't override
      }
    }

    const activeLink = tocList.querySelector(`.scrollspy-link[href="#${current.id}"]`);
    setActive(activeLink);
  }

  // On click: immediately highlight + lock onto target heading
  tocLinks.forEach(link => {
    link.addEventListener('click', function() {
      setActive(this);
      lockedHeadingId = this.getAttribute('href').slice(1);
    });
  });

  // Set initial state on load
  updateActive();

  // Update on scroll
  window.addEventListener('scroll', updateActive, { passive: true });
});
</script>
<script>
(function() {
  const ASCII = `     ██╗ ██████╗██████╗
     ██║██╔════╝██╔══██╗
     ██║██║     ██████╔╝
██   ██║██║     ██╔═══╝
╚█████╔╝╚██████╗██║
 ╚════╝  ╚═════╝╚═╝`;

  function esc(s) {
    return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  }

  function homeChrome() {
    return `<nav class="t-tabs" aria-label="Main navigation">
      ${['home', 'about', 'articles', 'projects', 'contact'].map(t => `<a href="${t === 'home' ? '/' : '/' + t + '/'}" class="t-tab${t === 'home' ? ' t-tab-active' : ''}"${t === 'home' ? ' aria-current="page"' : ''}><span class="t-tab-indicator" aria-hidden="true">${t === 'home' ? '▸' : '&nbsp;'}</span>${t}</a>`).join('')}
      <div class="t-tabs-spacer"></div><div class="t-title">jcp@joshpearlson: ~/</div>
    </nav>`;
  }

  function latestCard(post) {
    const tags = post.cats.map(c => `<span class="t-chip">${esc(c)}</span>`).join('');
    const art = post.image
      ? `<div class="t-latest-visual"><img src="${esc(post.image)}" alt="" loading="lazy" /></div>`
      : '';
    return `<a href="${esc(post.href)}" class="t-latest-card${post.image ? ' t-latest-with-image' : ''}"><div class="t-latest-copy">
      <div class="t-latest-label"><strong>LATEST ARTICLE</strong><span>${esc(post.date)}</span></div>
      <h2 class="t-latest-title">${esc(post.title)}</h2>
      <div class="t-latest-excerpt">${esc(post.excerpt)}</div>
      <div class="t-latest-meta">${tags}<span class="t-read-arrow">Read article →</span></div>
    </div>${art}</a>`;
  }

  function renderHome(mount) {
    mount.innerHTML = homeChrome() + `<div class="t-body" id="t-body">
      <div class="t-hero"><div class="t-intro">
        <div class="t-command"><span class="t-prompt">$</span>whoami</div>
        <h1>Josh Pearlson<span aria-hidden="true">_</span></h1>
        <p class="t-role">Quant @ BlackRock.<br>I write about <span class="t-accent">markets & machines.</span></p>
        <div class="t-actions"><a class="t-primary" href="/articles/">Read the articles →</a><a class="t-text-link" href="/projects/">Explore projects →</a></div>
      </div><aside class="t-identity" aria-label="JCP terminal identity">
        <div class="t-identity-label"><span>~/identity.txt</span><span>UTF-8</span></div>
        <div class="t-ascii-frame"><pre class="t-ascii" aria-label="JCP ASCII logo">${ASCII}</pre></div>
        <div class="t-identity-footer"><span>finance / ML / probability</span><span class="t-accent">NYC</span></div>
      </aside></div>
      <section aria-label="Latest article"><div class="t-section-heading"><h2><span class="t-prompt">$</span>cat latest.md</h2><a href="/articles/">All articles →</a></div>
        <div id="t-latest-mount"><a class="t-text-link" href="/articles/">Browse the latest writing →</a></div>
      </section>
      <nav aria-label="Explore the site"><div class="t-section-heading"><h2><span class="t-prompt">$</span>ls ./</h2></div>
        <div class="t-ls-grid">
          <a href="/about/" class="t-ls-cell"><div class="t-ls-name">01 / about →</div><div class="t-ls-path">Background, research & interests</div></a>
          <a href="/projects/" class="t-ls-cell"><div class="t-ls-name">02 / projects →</div><div class="t-ls-path">Tools, experiments & things I’ve built</div></a>
          <a href="/contact/" class="t-ls-cell"><div class="t-ls-name">03 / contact →</div><div class="t-ls-path">Say hello. Cold emails welcome.</div></a>
        </div>
      </nav>
    </div><div class="t-status"><span><span class="t-status-dot">●</span> online</span><span id="t-status-count">Articles / projects</span><span class="t-status-weather" id="t-status-weather">New York, NY</span></div>`;
  }

  function updateWeather() {
    const el = document.getElementById('t-status-weather');
    if (!el) return;
    // Keep the location useful when the weather service is unavailable.
    el.textContent = 'New York, NY';
    fetch('https://api.open-meteo.com/v1/forecast?latitude=40.7128&longitude=-74.0060&current=temperature_2m&temperature_unit=fahrenheit')
      .then(r => { if (!r.ok) throw new Error('Weather unavailable'); return r.json(); })
      .then(d => {
        const temperature = d.current && d.current.temperature_2m;
        if (typeof temperature === 'number' && Number.isFinite(temperature)) el.textContent = `NYC ${Math.round(temperature)}°F`;
      }).catch(() => {});
  }

  function init() {
    const mount = document.getElementById('jcp-terminal');
    if (!mount) return; // Article chrome owns its own header and status bar.
    const isHome = location.pathname === '/' || location.pathname === '/index.html';
    if (isHome) renderHome(mount);
    mount.querySelectorAll('.t-tabs').forEach(nav => {
      nav.setAttribute('role', 'navigation');
      nav.setAttribute('aria-label', 'Main navigation');
    });
    mount.querySelectorAll('.t-tab-active').forEach(a => a.setAttribute('aria-current', 'page'));
    updateWeather();

    // Read Quarto's rendered listing so date, categories and images stay in sync.
    const listingUrl = new URL('/articles/', location.origin);
    const listing = document.querySelector('.quarto-listing');
    const getListing = listing ? Promise.resolve(document) : fetch(listingUrl)
      .then(r => { if (!r.ok) throw new Error('Listing unavailable'); return r.text(); })
      .then(html => new DOMParser().parseFromString(html, 'text/html'));
    getListing.then(doc => {
      const posts = Array.from(doc.querySelectorAll('.quarto-post'));
      const count = document.getElementById('t-status-count');
      if (count) count.textContent = `${posts.length} articles / 7 projects`;
      if (!isHome || !posts.length) return;
      const post = posts[0];
      const link = post.querySelector('.listing-title a');
      if (!link) return;
      const img = post.querySelector('.thumbnail img');
      const raw = (post.querySelector('.listing-description')?.textContent || '').trim().replace(/\s+/g, ' ');
      const clipped = raw.length > 230 ? raw.slice(0, 227).replace(/\s+\S*$/, '') + '…' : raw;
      const sentenceEnd = Math.max(clipped.lastIndexOf('. '), clipped.lastIndexOf('! '), clipped.lastIndexOf('? '));
      const excerpt = sentenceEnd > 60 ? clipped.slice(0, sentenceEnd + 1) : clipped;
      document.getElementById('t-latest-mount').innerHTML = latestCard({
        href: new URL(link.getAttribute('href'), listingUrl).href,
        title: link.textContent.trim(), excerpt,
        date: post.querySelector('.listing-date')?.textContent.trim() || '',
        cats: Array.from(post.querySelectorAll('.listing-category')).map(c => c.textContent.trim()),
        image: img?.getAttribute('src') ? new URL(img.getAttribute('src'), listingUrl).href : ''
      });
    }).catch(() => {});
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>